services:
  frontend:
    image: frontend
    ports:
      - "8501:8501"
    # environment:
    #   - PREDICTION_URL=http://backend:8000/uploader
    env_file:
      - .env.local

    # networks:
    #   - front-tier
    #   - back-tier
    # configs:
    #   - httpd-config
    # secrets:
    #   - server-certificate

  backend:
    image: beating_heart_of_art:dev
    ports:
      - "8000:8000"
    env_file:
      - ../api/.env
    # volumes:
    #   - db-data:/etc/data
    # networks:
    #   - back-tier

# volumes:
#   db-data:
#     driver: flocker
#     driver_opts:
#       size: "10GiB"

# configs:
#   httpd-config:
#     external: true

# secrets:
#   server-certificate:
#     external: true

# networks:
#   # The presence of these objects is sufficient to define them
#   front-tier: {}
  # back-tier: {}